### ISSUE TITLE
Script não funciona

### ISSUE THREAD

**Issue by marconimedeiros** [GabrielRocha/pycnpj#1]
Quando eu rodo o script abaixo aparece o erro: 

> AttributeError: 'NoneType' object has no attribute 'razao_social'

`import pycnpj
sefaz_captcha = pycnpj.generate_captcha()
sefaz_captcha.get('captcha')
sefaz_captcha.get('validate_captcha')

empresa = pycnpj.consult_sefaz(sefaz_captcha.get('validate_captcha'), 'AsCv98', '06.990.590/0002-04')
print(empresa.razao_social)
print(empresa.json())`

Por favor, @GabrielRocha, você pode colocar um código válido?

**Comment by GabrielRocha** [comment]
@marconimedeiros ,
Adicionei novas informações no README do projeto.
O sistema precisa que você resolva o captcha e passe no consult_sefaz
```
pycnpj.consult_sefaz(sefaz_captcha.get('validate_captcha'), '<RESPOSTA DO CAPTCHA>', '06.990.590/0002-04')
```
Att,
